/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "center_server_constants.h"

namespace community { namespace center_server {

const center_serverConstants g_center_server_constants;

center_serverConstants::center_serverConstants() {
}

}} // namespace

