/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "room_server_constants.h"

namespace community { namespace room_server {

const room_serverConstants g_room_server_constants;

room_serverConstants::room_serverConstants() {
}

}} // namespace

