/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "common_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace community { namespace common {

int _kMessageTypeValues[] = {
  MessageType::MT_HELLO_REQ,
  MessageType::MT_HELLO_RES,
  MessageType::MT_HELLO_NOTIFY,
  MessageType::MT_KEEPALIVE_REQ,
  MessageType::MT_KEEPALIVE_RES
};
const char* _kMessageTypeNames[] = {
  "MT_HELLO_REQ",
  "MT_HELLO_RES",
  "MT_HELLO_NOTIFY",
  "MT_KEEPALIVE_REQ",
  "MT_KEEPALIVE_RES"
};
const std::map<int, const char*> _MessageType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kMessageTypeValues, _kMessageTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kErrorCodeValues[] = {
  ErrorCode::OK,
  ErrorCode::TICKET_INVALID,
  ErrorCode::LOGNAME_EXIST,
  ErrorCode::LOGNAME_NOT_EXIST,
  ErrorCode::PASSWORD_ERROR,
  ErrorCode::USERID_INVALID,
  ErrorCode::PASS_EXPIRYDATE,
  ErrorCode::ACCOUNT_LOCKED,
  ErrorCode::INVALID_ACCOUNT,
  ErrorCode::CLIENT_VERSION_INVALID,
  ErrorCode::ACCOUNT_ACCTIVED,
  ErrorCode::VERIFYCODE_VERIFIED,
  ErrorCode::USER_IN_BLACKLIST,
  ErrorCode::LOGIN_CONNECT_ERROR,
  ErrorCode::ROOMGATE_CONNECT_ERROR,
  ErrorCode::NICKNAME_DUPLICATE,
  ErrorCode::ROOM_UNKNOWN,
  ErrorCode::ROOM_STATUS_NO_STARTUP,
  ErrorCode::ROOM_STATUS_CLOSE,
  ErrorCode::ROOM_STATUS_LOCKED,
  ErrorCode::ROOM_USER_TICKET_INVALID,
  ErrorCode::ROOM_USER_ID_INVALID,
  ErrorCode::ROOM_USER_NO_AUTHORITY,
  ErrorCode::ROOM_USER_MONEY_LESS,
  ErrorCode::ROOM_USER_KICK_OUT,
  ErrorCode::ROOM_USER_OTHER_LOCAL_LOGIN,
  ErrorCode::ROOM_USER_COUNT_MAX,
  ErrorCode::ROOM_NEED_PASSWORD,
  ErrorCode::ROOM_PASSORD_ERROR,
  ErrorCode::ROOM_TO_USERID_INVALID,
  ErrorCode::REQUEST_ERROR,
  ErrorCode::REQUEST_TIMEOUT,
  ErrorCode::DB_CONNECT_ERROR,
  ErrorCode::DB_OPERATION_EXCEPTION,
  ErrorCode::SYSTEM_BUSY,
  ErrorCode::UNKOWN_ERROR
};
const char* _kErrorCodeNames[] = {
  "OK",
  "TICKET_INVALID",
  "LOGNAME_EXIST",
  "LOGNAME_NOT_EXIST",
  "PASSWORD_ERROR",
  "USERID_INVALID",
  "PASS_EXPIRYDATE",
  "ACCOUNT_LOCKED",
  "INVALID_ACCOUNT",
  "CLIENT_VERSION_INVALID",
  "ACCOUNT_ACCTIVED",
  "VERIFYCODE_VERIFIED",
  "USER_IN_BLACKLIST",
  "LOGIN_CONNECT_ERROR",
  "ROOMGATE_CONNECT_ERROR",
  "NICKNAME_DUPLICATE",
  "ROOM_UNKNOWN",
  "ROOM_STATUS_NO_STARTUP",
  "ROOM_STATUS_CLOSE",
  "ROOM_STATUS_LOCKED",
  "ROOM_USER_TICKET_INVALID",
  "ROOM_USER_ID_INVALID",
  "ROOM_USER_NO_AUTHORITY",
  "ROOM_USER_MONEY_LESS",
  "ROOM_USER_KICK_OUT",
  "ROOM_USER_OTHER_LOCAL_LOGIN",
  "ROOM_USER_COUNT_MAX",
  "ROOM_NEED_PASSWORD",
  "ROOM_PASSORD_ERROR",
  "ROOM_TO_USERID_INVALID",
  "REQUEST_ERROR",
  "REQUEST_TIMEOUT",
  "DB_CONNECT_ERROR",
  "DB_OPERATION_EXCEPTION",
  "SYSTEM_BUSY",
  "UNKOWN_ERROR"
};
const std::map<int, const char*> _ErrorCode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(36, _kErrorCodeValues, _kErrorCodeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));


ServiceAddr::~ServiceAddr() throw() {
}


void ServiceAddr::__set_ip(const std::string& val) {
  this->ip = val;
}

void ServiceAddr::__set_port(const int16_t val) {
  this->port = val;
}

uint32_t ServiceAddr::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->ip);
          this->__isset.ip = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->port);
          this->__isset.port = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ServiceAddr::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServiceAddr");

  xfer += oprot->writeFieldBegin("ip", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->ip);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("port", ::apache::thrift::protocol::T_I16, 2);
  xfer += oprot->writeI16(this->port);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServiceAddr &a, ServiceAddr &b) {
  using ::std::swap;
  swap(a.ip, b.ip);
  swap(a.port, b.port);
  swap(a.__isset, b.__isset);
}

ServiceAddr::ServiceAddr(const ServiceAddr& other0) {
  ip = other0.ip;
  port = other0.port;
  __isset = other0.__isset;
}
ServiceAddr& ServiceAddr::operator=(const ServiceAddr& other1) {
  ip = other1.ip;
  port = other1.port;
  __isset = other1.__isset;
  return *this;
}
void ServiceAddr::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServiceAddr(";
  out << "ip=" << to_string(ip);
  out << ", " << "port=" << to_string(port);
  out << ")";
}


ServiceInfo::~ServiceInfo() throw() {
}


void ServiceInfo::__set_service_id(const int32_t val) {
  this->service_id = val;
}

void ServiceInfo::__set_service_name(const std::string& val) {
  this->service_name = val;
}

void ServiceInfo::__set_service_weight(const int16_t val) {
  this->service_weight = val;
}

void ServiceInfo::__set_service_addr(const ServiceAddr& val) {
  this->service_addr = val;
}

uint32_t ServiceInfo::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->service_id);
          this->__isset.service_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->service_name);
          this->__isset.service_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->service_weight);
          this->__isset.service_weight = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->service_addr.read(iprot);
          this->__isset.service_addr = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ServiceInfo::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServiceInfo");

  xfer += oprot->writeFieldBegin("service_id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->service_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("service_name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->service_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("service_weight", ::apache::thrift::protocol::T_I16, 3);
  xfer += oprot->writeI16(this->service_weight);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("service_addr", ::apache::thrift::protocol::T_STRUCT, 4);
  xfer += this->service_addr.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServiceInfo &a, ServiceInfo &b) {
  using ::std::swap;
  swap(a.service_id, b.service_id);
  swap(a.service_name, b.service_name);
  swap(a.service_weight, b.service_weight);
  swap(a.service_addr, b.service_addr);
  swap(a.__isset, b.__isset);
}

ServiceInfo::ServiceInfo(const ServiceInfo& other2) {
  service_id = other2.service_id;
  service_name = other2.service_name;
  service_weight = other2.service_weight;
  service_addr = other2.service_addr;
  __isset = other2.__isset;
}
ServiceInfo& ServiceInfo::operator=(const ServiceInfo& other3) {
  service_id = other3.service_id;
  service_name = other3.service_name;
  service_weight = other3.service_weight;
  service_addr = other3.service_addr;
  __isset = other3.__isset;
  return *this;
}
void ServiceInfo::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServiceInfo(";
  out << "service_id=" << to_string(service_id);
  out << ", " << "service_name=" << to_string(service_name);
  out << ", " << "service_weight=" << to_string(service_weight);
  out << ", " << "service_addr=" << to_string(service_addr);
  out << ")";
}


HelloReq::~HelloReq() throw() {
}


void HelloReq::__set_service_info(const ServiceInfo& val) {
  this->service_info = val;
}

uint32_t HelloReq::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->service_info.read(iprot);
          this->__isset.service_info = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HelloReq::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("HelloReq");

  xfer += oprot->writeFieldBegin("service_info", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->service_info.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(HelloReq &a, HelloReq &b) {
  using ::std::swap;
  swap(a.service_info, b.service_info);
  swap(a.__isset, b.__isset);
}

HelloReq::HelloReq(const HelloReq& other4) {
  service_info = other4.service_info;
  __isset = other4.__isset;
}
HelloReq& HelloReq::operator=(const HelloReq& other5) {
  service_info = other5.service_info;
  __isset = other5.__isset;
  return *this;
}
void HelloReq::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "HelloReq(";
  out << "service_info=" << to_string(service_info);
  out << ")";
}


HelloNotify::~HelloNotify() throw() {
}


void HelloNotify::__set_error_code(const int16_t val) {
  this->error_code = val;
}

void HelloNotify::__set_error_text(const std::string& val) {
  this->error_text = val;
}

void HelloNotify::__set_service_name(const std::string& val) {
  this->service_name = val;
}

void HelloNotify::__set_service_id(const int32_t val) {
  this->service_id = val;
}

void HelloNotify::__set_server_random(const int64_t val) {
  this->server_random = val;
}

void HelloNotify::__set_server_time(const int64_t val) {
  this->server_time = val;
}

uint32_t HelloNotify::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->error_code);
          this->__isset.error_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->error_text);
          this->__isset.error_text = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->service_name);
          this->__isset.service_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->service_id);
          this->__isset.service_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->server_random);
          this->__isset.server_random = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->server_time);
          this->__isset.server_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HelloNotify::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("HelloNotify");

  xfer += oprot->writeFieldBegin("error_code", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->error_code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("error_text", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->error_text);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("service_name", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->service_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("service_id", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32(this->service_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_random", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->server_random);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("server_time", ::apache::thrift::protocol::T_I64, 6);
  xfer += oprot->writeI64(this->server_time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(HelloNotify &a, HelloNotify &b) {
  using ::std::swap;
  swap(a.error_code, b.error_code);
  swap(a.error_text, b.error_text);
  swap(a.service_name, b.service_name);
  swap(a.service_id, b.service_id);
  swap(a.server_random, b.server_random);
  swap(a.server_time, b.server_time);
  swap(a.__isset, b.__isset);
}

HelloNotify::HelloNotify(const HelloNotify& other6) {
  error_code = other6.error_code;
  error_text = other6.error_text;
  service_name = other6.service_name;
  service_id = other6.service_id;
  server_random = other6.server_random;
  server_time = other6.server_time;
  __isset = other6.__isset;
}
HelloNotify& HelloNotify::operator=(const HelloNotify& other7) {
  error_code = other7.error_code;
  error_text = other7.error_text;
  service_name = other7.service_name;
  service_id = other7.service_id;
  server_random = other7.server_random;
  server_time = other7.server_time;
  __isset = other7.__isset;
  return *this;
}
void HelloNotify::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "HelloNotify(";
  out << "error_code=" << to_string(error_code);
  out << ", " << "error_text=" << to_string(error_text);
  out << ", " << "service_name=" << to_string(service_name);
  out << ", " << "service_id=" << to_string(service_id);
  out << ", " << "server_random=" << to_string(server_random);
  out << ", " << "server_time=" << to_string(server_time);
  out << ")";
}


SessionTicket::~SessionTicket() throw() {
}


void SessionTicket::__set_user_id(const int32_t val) {
  this->user_id = val;
}

void SessionTicket::__set_user_name(const std::string& val) {
  this->user_name = val;
}

void SessionTicket::__set_email(const std::string& val) {
  this->email = val;
}

void SessionTicket::__set_nick_name(const std::string& val) {
  this->nick_name = val;
}

void SessionTicket::__set_client_ip(const std::string& val) {
  this->client_ip = val;
}

void SessionTicket::__set_client_mac(const std::string& val) {
  this->client_mac = val;
}

void SessionTicket::__set_client_version(const std::string& val) {
  this->client_version = val;
}

void SessionTicket::__set_app_id(const int32_t val) {
  this->app_id = val;
}

void SessionTicket::__set_session_id(const std::string& val) {
  this->session_id = val;
}

void SessionTicket::__set_session_key(const std::string& val) {
  this->session_key = val;
}

void SessionTicket::__set_create_time(const int64_t val) {
  this->create_time = val;
}

void SessionTicket::__set_end_time(const int64_t val) {
  this->end_time = val;
}

uint32_t SessionTicket::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->user_id);
          this->__isset.user_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->user_name);
          this->__isset.user_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->email);
          this->__isset.email = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->nick_name);
          this->__isset.nick_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->client_ip);
          this->__isset.client_ip = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->client_mac);
          this->__isset.client_mac = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->client_version);
          this->__isset.client_version = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->app_id);
          this->__isset.app_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->session_id);
          this->__isset.session_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->session_key);
          this->__isset.session_key = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->create_time);
          this->__isset.create_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->end_time);
          this->__isset.end_time = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SessionTicket::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SessionTicket");

  xfer += oprot->writeFieldBegin("user_id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->user_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("user_name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->user_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("email", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->email);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("nick_name", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->nick_name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("client_ip", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->client_ip);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("client_mac", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->client_mac);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("client_version", ::apache::thrift::protocol::T_STRING, 7);
  xfer += oprot->writeString(this->client_version);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("app_id", ::apache::thrift::protocol::T_I32, 8);
  xfer += oprot->writeI32(this->app_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("session_id", ::apache::thrift::protocol::T_STRING, 9);
  xfer += oprot->writeString(this->session_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("session_key", ::apache::thrift::protocol::T_STRING, 10);
  xfer += oprot->writeString(this->session_key);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("create_time", ::apache::thrift::protocol::T_I64, 11);
  xfer += oprot->writeI64(this->create_time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("end_time", ::apache::thrift::protocol::T_I64, 12);
  xfer += oprot->writeI64(this->end_time);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SessionTicket &a, SessionTicket &b) {
  using ::std::swap;
  swap(a.user_id, b.user_id);
  swap(a.user_name, b.user_name);
  swap(a.email, b.email);
  swap(a.nick_name, b.nick_name);
  swap(a.client_ip, b.client_ip);
  swap(a.client_mac, b.client_mac);
  swap(a.client_version, b.client_version);
  swap(a.app_id, b.app_id);
  swap(a.session_id, b.session_id);
  swap(a.session_key, b.session_key);
  swap(a.create_time, b.create_time);
  swap(a.end_time, b.end_time);
  swap(a.__isset, b.__isset);
}

SessionTicket::SessionTicket(const SessionTicket& other8) {
  user_id = other8.user_id;
  user_name = other8.user_name;
  email = other8.email;
  nick_name = other8.nick_name;
  client_ip = other8.client_ip;
  client_mac = other8.client_mac;
  client_version = other8.client_version;
  app_id = other8.app_id;
  session_id = other8.session_id;
  session_key = other8.session_key;
  create_time = other8.create_time;
  end_time = other8.end_time;
  __isset = other8.__isset;
}
SessionTicket& SessionTicket::operator=(const SessionTicket& other9) {
  user_id = other9.user_id;
  user_name = other9.user_name;
  email = other9.email;
  nick_name = other9.nick_name;
  client_ip = other9.client_ip;
  client_mac = other9.client_mac;
  client_version = other9.client_version;
  app_id = other9.app_id;
  session_id = other9.session_id;
  session_key = other9.session_key;
  create_time = other9.create_time;
  end_time = other9.end_time;
  __isset = other9.__isset;
  return *this;
}
void SessionTicket::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SessionTicket(";
  out << "user_id=" << to_string(user_id);
  out << ", " << "user_name=" << to_string(user_name);
  out << ", " << "email=" << to_string(email);
  out << ", " << "nick_name=" << to_string(nick_name);
  out << ", " << "client_ip=" << to_string(client_ip);
  out << ", " << "client_mac=" << to_string(client_mac);
  out << ", " << "client_version=" << to_string(client_version);
  out << ", " << "app_id=" << to_string(app_id);
  out << ", " << "session_id=" << to_string(session_id);
  out << ", " << "session_key=" << to_string(session_key);
  out << ", " << "create_time=" << to_string(create_time);
  out << ", " << "end_time=" << to_string(end_time);
  out << ")";
}


CommonNull::~CommonNull() throw() {
}


uint32_t CommonNull::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CommonNull::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CommonNull");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CommonNull &a, CommonNull &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

CommonNull::CommonNull(const CommonNull& other10) {
  (void) other10;
}
CommonNull& CommonNull::operator=(const CommonNull& other11) {
  (void) other11;
  return *this;
}
void CommonNull::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CommonNull(";
  out << ")";
}


CommonRes::~CommonRes() throw() {
}


void CommonRes::__set_error_code(const int16_t val) {
  this->error_code = val;
}

void CommonRes::__set_error_text(const std::string& val) {
  this->error_text = val;
}

uint32_t CommonRes::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->error_code);
          this->__isset.error_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->error_text);
          this->__isset.error_text = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t CommonRes::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CommonRes");

  xfer += oprot->writeFieldBegin("error_code", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->error_code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("error_text", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->error_text);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CommonRes &a, CommonRes &b) {
  using ::std::swap;
  swap(a.error_code, b.error_code);
  swap(a.error_text, b.error_text);
  swap(a.__isset, b.__isset);
}

CommonRes::CommonRes(const CommonRes& other12) {
  error_code = other12.error_code;
  error_text = other12.error_text;
  __isset = other12.__isset;
}
CommonRes& CommonRes::operator=(const CommonRes& other13) {
  error_code = other13.error_code;
  error_text = other13.error_text;
  __isset = other13.__isset;
  return *this;
}
void CommonRes::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CommonRes(";
  out << "error_code=" << to_string(error_code);
  out << ", " << "error_text=" << to_string(error_text);
  out << ")";
}


KeepAliveReq::~KeepAliveReq() throw() {
}


void KeepAliveReq::__set_req_id(const int32_t val) {
  this->req_id = val;
}

void KeepAliveReq::__set_current_time_req(const int64_t val) {
  this->current_time_req = val;
}

void KeepAliveReq::__set_network_status_level(const int16_t val) {
  this->network_status_level = val;
}

uint32_t KeepAliveReq::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->req_id);
          this->__isset.req_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->current_time_req);
          this->__isset.current_time_req = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->network_status_level);
          this->__isset.network_status_level = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t KeepAliveReq::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("KeepAliveReq");

  xfer += oprot->writeFieldBegin("req_id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->req_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("current_time_req", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->current_time_req);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("network_status_level", ::apache::thrift::protocol::T_I16, 3);
  xfer += oprot->writeI16(this->network_status_level);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(KeepAliveReq &a, KeepAliveReq &b) {
  using ::std::swap;
  swap(a.req_id, b.req_id);
  swap(a.current_time_req, b.current_time_req);
  swap(a.network_status_level, b.network_status_level);
  swap(a.__isset, b.__isset);
}

KeepAliveReq::KeepAliveReq(const KeepAliveReq& other14) {
  req_id = other14.req_id;
  current_time_req = other14.current_time_req;
  network_status_level = other14.network_status_level;
  __isset = other14.__isset;
}
KeepAliveReq& KeepAliveReq::operator=(const KeepAliveReq& other15) {
  req_id = other15.req_id;
  current_time_req = other15.current_time_req;
  network_status_level = other15.network_status_level;
  __isset = other15.__isset;
  return *this;
}
void KeepAliveReq::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "KeepAliveReq(";
  out << "req_id=" << to_string(req_id);
  out << ", " << "current_time_req=" << to_string(current_time_req);
  out << ", " << "network_status_level=" << to_string(network_status_level);
  out << ")";
}


KeepAliveRes::~KeepAliveRes() throw() {
}


void KeepAliveRes::__set_error_code(const int16_t val) {
  this->error_code = val;
}

void KeepAliveRes::__set_error_text(const std::string& val) {
  this->error_text = val;
}

void KeepAliveRes::__set_req_id(const int32_t val) {
  this->req_id = val;
}

void KeepAliveRes::__set_current_time_req(const int64_t val) {
  this->current_time_req = val;
}

void KeepAliveRes::__set_current_time_res(const int64_t val) {
  this->current_time_res = val;
}

uint32_t KeepAliveRes::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->error_code);
          this->__isset.error_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->error_text);
          this->__isset.error_text = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->req_id);
          this->__isset.req_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->current_time_req);
          this->__isset.current_time_req = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->current_time_res);
          this->__isset.current_time_res = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t KeepAliveRes::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("KeepAliveRes");

  xfer += oprot->writeFieldBegin("error_code", ::apache::thrift::protocol::T_I16, 1);
  xfer += oprot->writeI16(this->error_code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("error_text", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->error_text);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("req_id", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->req_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("current_time_req", ::apache::thrift::protocol::T_I64, 4);
  xfer += oprot->writeI64(this->current_time_req);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("current_time_res", ::apache::thrift::protocol::T_I64, 5);
  xfer += oprot->writeI64(this->current_time_res);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(KeepAliveRes &a, KeepAliveRes &b) {
  using ::std::swap;
  swap(a.error_code, b.error_code);
  swap(a.error_text, b.error_text);
  swap(a.req_id, b.req_id);
  swap(a.current_time_req, b.current_time_req);
  swap(a.current_time_res, b.current_time_res);
  swap(a.__isset, b.__isset);
}

KeepAliveRes::KeepAliveRes(const KeepAliveRes& other16) {
  error_code = other16.error_code;
  error_text = other16.error_text;
  req_id = other16.req_id;
  current_time_req = other16.current_time_req;
  current_time_res = other16.current_time_res;
  __isset = other16.__isset;
}
KeepAliveRes& KeepAliveRes::operator=(const KeepAliveRes& other17) {
  error_code = other17.error_code;
  error_text = other17.error_text;
  req_id = other17.req_id;
  current_time_req = other17.current_time_req;
  current_time_res = other17.current_time_res;
  __isset = other17.__isset;
  return *this;
}
void KeepAliveRes::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "KeepAliveRes(";
  out << "error_code=" << to_string(error_code);
  out << ", " << "error_text=" << to_string(error_text);
  out << ", " << "req_id=" << to_string(req_id);
  out << ", " << "current_time_req=" << to_string(current_time_req);
  out << ", " << "current_time_res=" << to_string(current_time_res);
  out << ")";
}

}} // namespace
