/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef room_server_CONSTANTS_H
#define room_server_CONSTANTS_H

#include "room_server_types.h"

namespace community { namespace room_server {

class room_serverConstants {
 public:
  room_serverConstants();

};

extern const room_serverConstants g_room_server_constants;

}} // namespace

#endif
