
#pragma once

//#define CRTDBG_MAP_ALLOC
//#include <stdlib.h>
//#include <crtdbg.h>

#define WM_RPC_MESSAGE			(WM_USER + 100)


#define SERVER_IP_ADDRESS		"127.0.0.1"
#define SERVER_PORT				9090
#define DEFAULT_USERNAME		123123
#define DEFAULT_PASSWORD		111111
#define SENDING_INTERVAL_MS		300
#define DEFAULT_MESSAGE_LEN		TEXT_DATA_LEN
#define THREAD_NUM				1
#define CHAT_TIMES				-1
#define TEXT_DATA_LEN			TCP_RECVBUFF_MAX_LEN
#define TCP_RECVBUFF_LEN_MAX	(1024 * 16)

typedef enum
{
	RPC_HELLO_NOTIFY,
	RPC_MESSAGE_LOGIN_RESP,
	RPC_MESSAGE_CHAT_NOTIFY,
	PRC_MESSAGE_LOGOUT_RESP,
	RPC_MESSAGE_AVERAGE_CONSUMPTION,
	RPC_MESSAGE_MAX
}SL_RPC_MESSAGE;